### ISSUE TITLE
[Feature Request] Option to disable parity check & mover pausing

### ISSUE THREAD

**Issue by alex-cardenas** [pairofcrocs/qbit-unraid-slowdown#5]
It would be great to offer the end user the option of enabling/disabling the Parity Check pausing and Mover pausing feature. 

In the meantime, if this could be accomplished by "simply" deleting the referenced python code (or commenting out), instructions on how to do that would be greatly appreciated. 

I could try testing it on my server; I have a parity check starting up tomorrow. 

Thanks

**Comment by pairofcrocs** [comment]
I'm going to close this issue as it's out of scope. However, with some simple modifications of the script, you could make this happen pretty easily :)
